import { useQuery } from '@tanstack/react-query'
import { motion } from 'framer-motion'
import { aiApi } from '../lib/api'
import { getInsightIcon, formatKES } from '../lib/utils'

const INSIGHT_STYLES: Record<string, { bg: string, border: string, color: string }> = {
  warning: { bg: 'rgba(245,158,11,0.08)', border: 'rgba(245,158,11,0.2)', color: '#f59e0b' },
  tip: { bg: 'rgba(124,58,237,0.08)', border: 'rgba(124,58,237,0.2)', color: '#a855f7' },
  achievement: { bg: 'rgba(16,185,129,0.08)', border: 'rgba(16,185,129,0.2)', color: '#10b981' },
  alert: { bg: 'rgba(239,68,68,0.08)', border: 'rgba(239,68,68,0.2)', color: '#ef4444' },
  general: { bg: 'rgba(59,130,246,0.08)', border: 'rgba(59,130,246,0.2)', color: '#3b82f6' },
}

const TYPE_LABELS: Record<string, string> = {
  warning: '⚠️ Warning',
  tip: '💡 Tip',
  achievement: '🏆 Achievement',
  alert: '🚨 Alert',
  general: '📊 Insight',
}

export default function InsightsPage() {
  const { data, isLoading } = useQuery({
    queryKey: ['insights'],
    queryFn: () => aiApi.insights().then(r => r.data),
    staleTime: 1000 * 60 * 5, // Cache for 5 minutes
  })

  const insights = data?.insights ?? []
  const isAIPowered = data?.ai_powered

  return (
    <div className="page-container">
      {/* AI Mode Banner */}
      <motion.div
        initial={{ opacity: 0, y: -5 }} animate={{ opacity: 1, y: 0 }}
        className="flex items-center gap-3 px-4 py-3 rounded-xl mb-6"
        style={{
          background: isAIPowered ? 'rgba(124,58,237,0.08)' : 'rgba(245,158,11,0.08)',
          border: isAIPowered ? '1px solid rgba(124,58,237,0.2)' : '1px solid rgba(245,158,11,0.2)',
        }}
      >
        <span className="text-lg">{isAIPowered ? '🤖' : '📊'}</span>
        <div>
          <p className="text-sm font-semibold" style={{ color: isAIPowered ? 'var(--purple-light)' : '#f59e0b' }}>
            {isAIPowered ? 'AI-Powered Insights Active' : 'Analytics-Based Insights'}
          </p>
          <p className="text-xs" style={{ color: 'var(--text-muted)' }}>
            {isAIPowered
              ? 'Insights generated by GPT-4o based on your real financial data'
              : 'Add your OpenAI API key to enable AI-powered insights'}
          </p>
        </div>
      </motion.div>

      {isLoading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {[...Array(6)].map((_, i) => <div key={i} className="h-36 rounded-2xl shimmer" />)}
        </div>
      ) : insights.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-20">
          <div className="text-5xl mb-4">📊</div>
          <h2 className="text-xl font-bold mb-2">No insights yet</h2>
          <p className="text-sm" style={{ color: 'var(--text-muted)' }}>
            Add transactions to start receiving personalized financial insights
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {insights.map((insight: any, i: number) => {
            const style = INSIGHT_STYLES[insight.type] ?? INSIGHT_STYLES.general
            return (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.06 }}
                className="rounded-2xl p-5 hover:scale-[1.01] transition-transform"
                style={{ background: style.bg, border: `1px solid ${style.border}` }}
              >
                <div className="flex items-start gap-3">
                  <span className="text-2xl flex-shrink-0">{getInsightIcon(insight.type)}</span>
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-2">
                      <span className="text-xs font-semibold px-2 py-0.5 rounded-full"
                        style={{ background: `${style.color}20`, color: style.color }}>
                        {TYPE_LABELS[insight.type] ?? '📊 Insight'}
                      </span>
                      {insight.category && (
                        <span className="text-xs px-2 py-0.5 rounded-full"
                          style={{ background: 'var(--bg-card)', color: 'var(--text-muted)' }}>
                          {insight.category}
                        </span>
                      )}
                    </div>
                    <p className="text-sm leading-relaxed" style={{ color: 'var(--text-primary)' }}>
                      {insight.text}
                    </p>
                    {insight.value && typeof insight.value === 'number' && insight.value > 1000 && (
                      <p className="text-xs mt-2 font-semibold" style={{ color: style.color }}>
                        Amount: {formatKES(insight.value)}
                      </p>
                    )}
                  </div>
                </div>
              </motion.div>
            )
          })}
        </div>
      )}
    </div>
  )
}
